conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('games.urls', namespace='game'))
]

games/urls.py
from django.urls import path
from games.views import GameListView, GameDetailView, GameCreateView, GameUpdateView, GameDeleteView

app_name = 'games'


urlpatterns = [
    path('', GameListView.as_view(), name='list'),
    path('<int:pk>/', GameDetailView.as_view(), name='detail'),
    path('create/', GameCreateView.as_view(), name='create'),
    path('<int:pk>/update/', GameUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', GameDeleteView.as_view(), name='delete')
]

games/models.py
from django.db import models

class GamesModel(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    link = models.URLField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Games'
        verbose_name = 'Game'

games/forms.py
from django import forms
from games.models import GamesModel


class GameForm(forms.ModelForm):
    class Meta:
        model = GamesModel
        fields = ['name', 'description', 'link']

games/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from games.forms import GameForm
from games.models import GamesModel


class GameListView(ListView):
    model = GamesModel
    template_name = 'games.html'
    context_object_name = 'games'


class GameDetailView(DetailView):
    model = GamesModel
    template_name = 'games_detail.html'
    context_object_name = 'game'


class GameCreateView(CreateView):
    model = GamesModel
    form_class = GameForm
    template_name = 'game_create.html'
    success_url = reverse_lazy('games:list')


class GameUpdateView(UpdateView):
    model = GamesModel
    form_class = GameForm
    template_name = 'game_update.html'
    success_url = reverse_lazy('games:list')
    context_object_name = 'game'


class GameDeleteView(DeleteView):
    model = GamesModel
    template_name = 'game_delete_confirm.html'
    success_url = reverse_lazy('games:list')
    context_object_name = 'game'

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        return get_object_or_404(GamesModel, pk=pk)

templates/game_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 20px;
            padding: 20px;
            background: linear-gradient(to bottom, #66a3ff, #007BFF);
            color: #fff;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            transition: background 0.3s ease;
        }

        form {
            max-width: 400px;
            margin: 0 auto;
            background-color: rgba(255, 255, 255, 0.9);
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            transition: box-shadow 0.3s ease;
        }

        h1 {
            color: #ffc107;
            text-align: center;
            margin-bottom: 20px;
        }

        label {
            display: block;
            margin-bottom: 8px;
            color: #333;
        }

        input {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ddd;
            border-radius: 5px;
            box-sizing: border-box;
        }

        button {
            background-color: #ffc107;
            color: #333;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease, color 0.3s ease;
        }

        button:hover {
            background-color: #ff8c00;
            color: #fff;
        }

        a {
            display: block;
            margin-top: 10px;
            text-decoration: none;
            color: #007BFF;
            transition: color 0.3s ease;
        }

        a:hover {
            color: #0056b3;
        }
    </style>
</head>
<body>
    <form action="{% url 'games:create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
    <a href="{% url 'games:list' %}">Back</a>
</body>
</html>

templates/game_delete_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 20px;
            padding: 20px;
            background: #3498db;
            color: #fff;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            transition: background 0.3s ease;
        }

         h1 {
            color: #ffc107;
            text-align: center;
            margin-bottom: 20px;
            font-size: 32px;
            font-weight: bold;
            text-transform: uppercase;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);
        }

        button {
            background-color: #ffc107;
            color: #333;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease, color 0.3s ease;
        }

        button:hover {
            background-color: #0056b3;
            color: #fff;
        }

        a {
            text-decoration: none;
        }

        a button {
            background-color: #ffc107;
            color: #fff;
            margin-top: 10px;
        }

        a button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>Rostan ham shu o'yinni o'chirmoqchimisiz? {{ game.name }}</h1>
    <form action="{% url 'games:delete' pk=game.id %}" method="post">
        {% csrf_token %}
        <button type="submit">Ha</button>
    </form>
    <a href="{% url 'games:list' %}"><button>Yo'q</button></a>
</body>
</html>

templates/game_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 20px;
            padding: 20px;
            background: linear-gradient(to bottom, #66a3ff, #007BFF);
            color: #fff;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            transition: background 0.3s ease;
        }

        form {
            max-width: 400px;
            margin: 0 auto;
            background-color: rgba(255, 255, 255, 0.9);
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            transition: box-shadow 0.3s ease;
        }

        h1 {
            color: #ffc107;
            text-align: center;
            margin-bottom: 20px;
        }

        label {
            display: block;
            margin-bottom: 8px;
            color: #333;
        }

        input {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ddd;
            border-radius: 5px;
            box-sizing: border-box;
        }

        button {
            background-color: #ffc107;
            color: #333;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease, color 0.3s ease;
        }

        button:hover {
            background-color: #ff8c00;
            color: #fff;
        }
    </style>
</head>
<body>
    <form action="{% url 'games:update' pk=game.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
</body>
</html>

templates/games.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Game</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 20px;
            padding: 20px;
            background: linear-gradient(to bottom, #66a3ff, #007BFF);
            color: #333;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            transition: background 0.3s ease;
        }

        h1 {
            color: #ffc107;
            text-align: center;
            margin-bottom: 20px;
        }

        a {
            text-decoration: none;
            color: #0056b3;
            transition: color 0.3s ease;
        }

        a:hover {
            color: #003366;
        }

        a#create-game {
            display: inline-block;
            padding: 10px 20px;
            margin-bottom: 20px;
            background-color: #ffc107;
            color: #333;
            border-radius: 5px;
            transition: background 0.3s ease;
        }

        a#create-game:hover {
            background-color: #ff8c00;
        }

        hr {
            border: none;
            border-top: 2px solid #ffc107;
            margin: 20px 0;
        }

        ul {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        li {
            margin: 15px 0;
            padding: 20px;
            background-color: rgba(255, 255, 255, 0.9);
            border-radius: 15px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            transition: box-shadow 0.3s ease;
        }

        li:hover {
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
            transform: scale(1.02);
        }
    </style>
</head>
<body>
    <h1>Games List</h1>
    <a href="{% url 'games:create' %}" id="create-game">Create game</a>
    <hr>
    <ul>
        {% for game in games %}
        <a href="{% url 'games:detail' pk=game.id %}">
            <li>{{ game.name }}</li>
        </a>
        {% endfor %}
    </ul>
</body>
</html>

templates/games_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 20px;
            padding: 20px;
            background: linear-gradient(to bottom, #66a3ff, #007BFF);
            color: #fff;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            transition: background 0.3s ease;
        }

        h1 {
            color: #ffc107;
            text-align: center;
            margin-bottom: 20px;
        }

        p {
            margin: 20px 0;
            line-height: 1.5;
            text-align: center;
        }

        a {
            display: inline-block;
            text-decoration: none;
            color: #007BFF;
            padding: 10px;
            margin: 10px 0;
            background-color: rgba(255, 255, 255, 0.9);
            border-radius: 5px;
            transition: background-color 0.3s ease, color 0.3s ease;
        }

        a:hover {
            background-color: #007BFF;
            color: #fff;
        }
    </style>
</head>
<body>
    <h1>{{ game.name }}</h1>
    <p>{{ game.description }}</p>
    <a href="{{ game.link }}">Download</a>
    <a href="{% url 'games:update' pk=game.id %}">Update</a>
    <a href="{% url 'games:delete' pk=game.id %}">Delete</a>
    <a href="{% url 'games:list' %}">Back</a>
</body>
</html>